version: '3.7'

services:
  springapi:
    container_name: "${PROJECTNAME}-springapi-${OPENJDKVERSION}"
    build:
      context: "${PROJECTROOT}"
      dockerfile: "docker/prod/dockerfiles/springapi/Dockerfile"
      args:
        OPENJDKVERSION: "${OPENJDKVERSION}"
        MAVEN_VERSION: "${MAVENVERSION}"
    ports:
      - "${SPRINGAPIPORT}:8080"
    working_dir: '/app'
    depends_on:
      - 'mysql'
    networks:
      main:
  angularwebapp:
    container_name: "${PROJECTNAME}-angularwebapp-${NODEJSVERSION}"
    build:
      context: "${PROJECTROOT}"
      dockerfile: "docker/prod/dockerfiles/angularwebapp/Dockerfile"
      args:
        NODEJSVERSION: "${NODEJSVERSION}"
        ANGULARROOT: "${NODEJSVERSION}"
    ports:
      - "${ANGULARPORT}:4200"
    working_dir: '/app'
    networks:
      main:
  mysql:
    container_name: "${PROJECTNAME}-mysql-${MYSQLVERSION}"
    image: "mysql:${MYSQLVERSION}"
    volumes:
      - "./mysql-${MYSQLVERSION}:/var/lib/mysql"
    working_dir: "/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=${ROOTPASS}"
      - "MYSQL_DATABASE=${DBNAME}"
      - "MYSQL_USER=${DBUSER}"
      - "MYSQL_PASSWORD=${DBPASS}"
    networks:
      main:
networks:
  main:
    name: "${PROJECTNAME}-main-network"